apiVersion: v1
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
  - name: alpine
    image: alpine
    command:
      - sh
      - -c
      - |
        apk update && apk add curl && sleep 3600
