# Stage 1
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app
COPY HelloWorld.java .
RUN javac HelloWorld.java
# Stage 2
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /app/HelloWorld.class .
CMD ["java", "HelloWorld"]
